print("Welcome To The Dictionary")
Dict = {}
Dict.update({"Python": "Programming Language"})
Dict.update({"Pycharm": "I.D.E"})
Dict.update({"Java": "Programming Language"})
Dict.update({"Visual Studio": "I.D.E"})
print("Enter The Word")
Word = input()
#Dict.capitalize()                                # this ia an error( i have to work on this )
print("The Meaning Is:", Dict[Word])
# print(Dict[Word])
# Dict.get(Word)
# print(Dict.get(Word))
print("\nThank You For Using The Dictionary")
